### ISSUE TITLE
Have a toggle to eliminate V8_DEPRECATE_SOON and friends

### ISSUE THREAD

**Issue by domenic** [paulfryzel/v8-doxygen#1]
Would be nice to have a clean reference to only the non-deprecated methods.

**Comment by paulfryzel** [comment]
@domenic Yeah, I agree. I'll look into doxygen's support for this OOTB. It may be possible via a doxygen preprocessor or filter. Otherwise, I could probably just write some external step to prune the include header before processing.

**Comment by domenic** [comment]
I was kind of an envisioning a client-side JS filter actually, but either works for me.

**Comment by paulfryzel** [comment]
Fixed via: https://github.com/paulfryzel/v8-doxygen/commit/456594694faf8c23110933880aa4a26fdbc0290e and https://github.com/paulfryzel/v8-doxygen/commit/f735f11cd86588a52a6127d5cab0226381d99641.

Big thanks to @pgoldrbx for most of the actual work!
